### ISSUE TITLE
Obtain API from IDIKA

### ISSUE THREAD

**Issue by bkbilly** [DsTyM/OnePrescriptionGR#1]
Hello, I am interested on using your application, but I can't find any instructions on how to get the API from IDIKA.
Could you help me with the process?

**Comment by DsTyM** [comment]
Hello, thanks for being interested for the app. To get an API key you have to contact IDIKA.
As it's stated on their site: https://www.e-prescription.gr/shs/portal/eprescription/contact/contactus , their phone number in Greece is: 11131.
I think you should call them, explain them why you need the API key (e.g. for Development / Research purposes) and they should you provide one

**Comment by bkbilly** [comment]
Thanks for the info!
I will call them to get the key.
I would recommend to write THIS info on the README.

**Comment by DsTyM** [comment]
I just included this info in README.md. Thanks for the suggestions.
